name: ci

on:
  pull_request:
    branches: master
  push:
    branches: master

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        version:
          - latest
          - 1.8.0
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Set up Go
        uses: actions/setup-go@master
      -
        name: Mage
        uses: ./
        with:
          version: ${{ matrix.version }}
          args: -version
