name: master

on:
  push:
    branches:
      - 'master'
    paths:
      - 'package.*'

jobs:
  prune:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Prune prod
        run: npm prune --production
      -
        name: Set up Git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
      -
        name: Lint check
        run: tslint './src/*.ts'
      -
        name: Commit and push changes
        run: |
          git add --all
          git status --short -uno
          git commit -m 'Update node_modules'
          git show --stat-count=10 HEAD
          git push -f origin master
